version: '3.9'

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/api/dev/Dockerfile
    image: fullstack_template_api_dev
    volumes:
      - ./api:/var/www/api
      - ./docker/api/dev/install.sh:/var/www/install.sh
    ports:
      - 80:8000
      - 443:8000
    restart: always
    depends_on:
      - db
    working_dir: /var/www/api
    container_name: dev_fullstack_api
    entrypoint: ["/bin/sh", "/var/www/install.sh"]

  db:
    build:
      context: ./
      dockerfile: ./docker/db/dev/Dockerfile
    image: fullstack_template_mysql_dev
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 1117:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gladkix
      MYSQL_USER: gladkix
      MYSQL_PASSWORD: 123456
    container_name: dev_fullstack_db

  app:
    build:
      context: ./
      dockerfile: ./docker/app/dev/Dockerfile
    image: fullstack_template_app_dev
    volumes:
      - ./app:/var/www/app
      - ./docker/app/dev/install.sh:/var/www/install.sh
    ports:
      - 7777:8080
    restart: always
    working_dir: /var/www/app
    container_name: dev_fullstack_app
    entrypoint: ["/bin/sh", "/var/www/install.sh"]

volumes:
  mysql:

